{% set version = "2.1.1" %}

package:
  name: mapclassify
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mapclassify/mapclassify-{{ version }}.tar.gz
  sha256: 6994f398dae83cc0aafd844b78a7596ee9ddb0f8c0c73bb0b1af3550056c98a8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.3
    - pandas
    - scipy >=0.11
    - scikit-learn
    - deprecated

test:
  imports:
    - mapclassify
    - mapclassify.datasets
    - mapclassify.datasets.calemp

about:
  home: https://github.com/pysal/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  dev_url: https://github.com/pysal/mapclassify

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
