{% set name = "mapclassify" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65fa7a7d778ed63496ff860b9f3c26d632d8f289820a6d8556ac527d14b26bd8

build:
  number: 0
  # Seems like the package is compatible with py>=38,
  # see https://github.com/pysal/mapclassify/tree/main/ci
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python
    - networkx >=3.2
    - numpy >=1.26
    - pandas >=2.1
    - scikit-learn >=1.4
    - scipy >=1.12
  run_constrained:
    - numba >=0.58

test:
  imports:
    - mapclassify
    - mapclassify.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pysal.org/mapclassify/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  description: |
    mapclassify implements a family of classification schemes for choropleth maps.
    Its focus is on the determination of the number of classes, and the assignment of observations to those classes.
    It is intended for use with upstream mapping and geovisualization packages (see geopandas and geoplot)
    that handle the rendering of the maps.
  dev_url: https://github.com/pysal/mapclassify
  doc_url: https://pysal.org/mapclassify/tutorial.html

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf