{% set name = "mapclassify" %}
{% set version = "2.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85dbfe747e5b5aed1f1fd41ef5de0c0ab8322227ee308191a44fff12c59c197d

build:
  number: 0
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - wheel
  run:
    - python
    - networkx >=3.4
    - numpy >=2.0
    - pandas >=2.3
    - scikit-learn >=1.5
    - scipy >=1.14
  run_constrained:
    - numba >=0.60

# Skip test_legendgram_map[png] because of 'pyogrio.errors.DataSourceError: None: No such file or directory'
{% set skip_tests = " --deselect=mapclassify/tests/test_legendgram.py::TestLegendgram::test_legendgram_map[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_legendgram.py::TestLegendgram::test_legendgram_most_recent_cmap[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_value_by_alpha.py::TestLegendgram::test_legendgram_position[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_value_by_alpha.py::TestValueByAlphaChoropleth::test_divergent_revert_alpha_min_alpha[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_value_by_alpha.py::TestValueByAlphaChoropleth::test_classify_xy_redblue[png] " %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_value_by_alpha.py::TestValueByAlphaChoropleth::test_pass_in_ax[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_value_by_alpha.py::TestValueByAlphaChoropleth::test_userdefined_colors[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_value_by_alpha.py::TestValueByAlphaChoropleth::test_shifted_colormap[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_value_by_alpha.py::TestValueByAlphaChoropleth::test_truncated_colormap[png]" %}
{% set skip_tests = skip_tests + " --deselect=mapclassify/tests/test_mapclassify.py::TestPlots::test_histogram_plot[png] " %}


test:
  imports:
    - mapclassify
    - mapclassify.datasets
  source_files:
# Use top level dir to avoid 'ImportError: attempted relative import beyond top-level package'
    - mapclassify
  requires:
    - pip
    - pytest
    - geopandas >=1.1.0
    - libpysal
    - matplotlib-base
    - shapely
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv {{ skip_tests }} mapclassify/tests


about:
  home: https://pysal.org/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  description: |
    mapclassify implements a family of classification schemes for choropleth maps.
    Its focus is on the determination of the number of classes, and the assignment of observations to those classes.
    It is intended for use with upstream mapping and geovisualization packages (see geopandas and geoplot)
    that handle the rendering of the maps.
  dev_url: https://github.com/pysal/mapclassify
  doc_url: https://pysal.org/mapclassify/tutorial.html

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
