{% set name = "mapclassify" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d6736a08c0b1e10e6197224ef512951514204706514244bd01aea49fd1442b3

build:
  number: 0
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - toml
    - wheel
  run:
    - python
    - networkx >=3.2
    - numpy >=1.26
    - pandas >=2.1
    - scikit-learn >=1.4
    - scipy >=1.12
    - pyogrio
  run_constrained:
    - numba >=0.58

{% set skip_tests = "" %}

# Ignore test because of 'ImportError: attempted relative import beyond top-level package'
{% set skip_tests = skip_tests + " --ignore=mapclassify/tests/test_mapclassify.py" %}
{% set skip_tests = skip_tests + " --ignore=mapclassify/tests/test_greedy.py" %}
{% set skip_tests = skip_tests + " --ignore=mapclassify/tests/test_classify.py" %}
{% set skip_tests = skip_tests + " --ignore=mapclassify/tests/test_legendgram.py" %}

# Skip test_legendgram_map[png] because of 'pyogrio.errors.DataSourceError: None: No such file or directory'

# Testing
{% set skip_tests = skip_tests + " --ignore=mapclassify/tests/test_value_by_alpha.py" %}

test:
  imports:
    - mapclassify
    - mapclassify.datasets
  source_files:
    - mapclassify/tests
  requires:
    - pip
    - pytest
    - pytest-xdist
    # earlier than 0.10.0 use ops.cascaded_union from shapely which was removed in 2.0.0
    - geopandas >=0.10.0
    - libpysal
    - matplotlib-base
    #  deprecated and was removed from version 2.0.0
    - shapely
  commands:
    - pip check
    
    - pytest -vv {{ skip_tests }} mapclassify/tests -k "not test_legendgram_map[png]"


about:
  home: https://pysal.org/mapclassify
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  description: |
    mapclassify implements a family of classification schemes for choropleth maps.
    Its focus is on the determination of the number of classes, and the assignment of observations to those classes.
    It is intended for use with upstream mapping and geovisualization packages (see geopandas and geoplot)
    that handle the rendering of the maps.
  dev_url: https://github.com/pysal/mapclassify
  doc_url: https://pysal.org/mapclassify/tutorial.html

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
