{% set name = 'mapclassify' %}
{% set version = "2.5.0" %}

package:
  name: mapclassify
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mapclassify/mapclassify-{{ version }}.tar.gz
  sha256: 5eb1f782155b5a90ec93c1dc52b300a2fad33117dcf08b7c858ed96da2a7baa0

build:
  number: 0
  # Seems like the package is compatible with py>=38,
  # see https://github.com/pysal/mapclassify/tree/main/ci
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - networkx
    - numpy >=1.3
    - pandas >=1.0
    - scikit-learn
    - scipy >=1.0

test:
  imports:
    - mapclassify
    - mapclassify.datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pysal.org/mapclassify/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Classification schemes for choropleth maps
  description: |
    mapclassify implements a family of classification schemes for choropleth maps. 
    Its focus is on the determination of the number of classes, and the assignment of observations to those classes. 
    It is intended for use with upstream mapping and geovisualization packages (see geopandas and geoplot) 
    that handle the rendering of the maps.
  dev_url: https://github.com/pysal/mapclassify
  doc_url: https://pysal.org/mapclassify/tutorial.html

extra:
  recipe-maintainers:
    - sjsrey
    - ljwolf
    - jorisvandenbossche
    - ocefpaf
