travis:
  secure:
    BINSTAR_TOKEN: KgcC9HqcIFupEJw5wVKCwDkMGestX6XzmwzToYG8YCMIvTrXDBIS+4TkqUykZbXuDABq4E7BpkE1VTQRddLzuArQvvAFXVq/VIx53CuK41UfKwh0f/NlnOsuVmauJiGT0liUZCnDNIRtI3tefHzYzUQL4YHQKPXlvoZi0vhKL75Rd/WDoy3sSVfeVfw91QiCkb8P4ICC5ll8EPlJwBlqumoR9cAUQ45YK2UDNvWkxObn7g7g1LjbX3iYvKs2F5OhvrJ1hDUZOPLjuhnFzGbolDxg2w+kxWXr1at6Myen+XVtCO41o7icmTO2dhvrydGHWEtKcSuJXkU4X9nMfI3UtW2/gOnxo84qsHRH3Q9vx1p1iozdK2oocMH+wJy2bJ0UqPrmq0R89JRJ7w2bgrYiJCPBj325REr8lK8i/SuilRaBhqfuJ/ryoejWQIBtIqCLv2mFnFwt0lAC2MXcXGOzhsmXRs5f/UVGzejAKtNYeLEPe33L6Y7Nv1/6zDhpIhGZDAIPMuwN7RMnngPX7cX+JatTsC8AyD6TrAecapd12zEiOfSqxPnSGqpvFk3Qozky+6TVJfAXQ+O+p9vHgX6oMtJB0Ysu8rb39IiTD1Ql8M5Pvj3E9JCCqbt9rp1ORbTHbuo0qMiGcY1s/dS12klfBK2rpf2Sf39oUDhrBNfC3/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
