travis:
  secure:
    BINSTAR_TOKEN: E7BasNOr/F+qUo/SbNcizMpHkQM1TR0V1w/zoM9zGgZOKCeG2JUx8rlA2wNiUvmN4JJS5QD/N8YgFeW+luFC3i9HDG1wTGkEY3NiMrvVsWUNSWpCFQsgV1iiFPtoOzPTFeIySijdaR8viXOCEw0ZMwfZ/DgDHBedpBzJ7OWuf/ISznCBG4Zb74FOk8rLir6sxw9nnugi+f88VfdXAzZqrYAjFhI4pKpgaWO3fFA7QHqYakhcLjVicg7pDpOkIn+3bUTVnWb1kUuJ75TBwVnW0TetqxtVlCQYrHm27iWMfiVxu9URblgL5QIsxJUXxQZfFQDzFz1Tcoklsg6yTN0TtHXe1TMkCOzdOTOrONiWtv5MGDZz11rdxgaJcMAtVhAvYwzwjl7swpypdF7dfQ8X3i/UyLxmIwKQkgxDCkq3rovu9avfn8UV3q93HzUmu8BqlHfx2FTs281mfRVlOjkytIepr1XjCM5TK0kZhIkbTwdWptXTd1zYfvBP6foHesvAF1R9StHwBnB53fxYIXfiSOGgIeYtpC0rfN4AYpqO3EryfC/f0dIHS9ZvgfQ5DekJPEOzPDVCWOhEerLEDcrLlC7Tox5pYL1aAK2ObBHugeB3T6ilhopP991AdqOqGK+sHBXr8E+WvGmsJRmnmIAGYGtHGpRU/5ap2OAWQu8Vjic=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
